"""“change3333333”

Revision ID: 290ae7866174
Revises: e11d2c020123
Create Date: 2022-06-17 13:29:02.060354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290ae7866174'
down_revision = 'e11d2c020123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
