"""“done123123”

Revision ID: 338d9a371f6e
Revises: 847a703b0389
Create Date: 2022-06-17 13:34:05.429448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338d9a371f6e'
down_revision = '847a703b0389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
