"""bb

Revision ID: 3804075e733a
Revises: 8ab3e9c4100d
Create Date: 2022-06-10 11:21:37.326206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3804075e733a'
down_revision = '8ab3e9c4100d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
