"""add chatting_histories model

Revision ID: 43eedcb6a89e
Revises: 68b0466690b5
Create Date: 2022-06-17 13:23:32.359607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eedcb6a89e'
down_revision = '68b0466690b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
