"""Edit User Model

Revision ID: 4ad2f9a39810
Revises: c9b2cbef3dae
Create Date: 2022-06-09 12:16:57.122357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad2f9a39810'
down_revision = 'c9b2cbef3dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
