"""Add column last_name to User model

Revision ID: 68b0466690b5
Revises: d50e1432a435
Create Date: 2022-06-12 04:43:00.324412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b0466690b5'
down_revision = 'd50e1432a435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_schedule_detail', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_schedule_detail', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
