"""edit table names

Revision ID: 7fa1438d1e71
Revises: 605519cd2d4a
Create Date: 2022-06-10 10:13:32.346791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa1438d1e71'
down_revision = '605519cd2d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_schedule_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_schedule_detail_id'), 'challenge_schedule_detail', ['id'], unique=False)
    op.create_table('challenge_user_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_user_detail_id'), 'challenge_user_detail', ['id'], unique=False)
    op.drop_index('ix_challengescheduledetail_id', table_name='challengescheduledetail')
    op.drop_table('challengescheduledetail')
    op.drop_index('ix_challengeuserdetail_id', table_name='challengeuserdetail')
    op.drop_table('challengeuserdetail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challengeuserdetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_master', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name='challengeuserdetail_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='challengeuserdetail_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challengeuserdetail_pkey')
    )
    op.create_index('ix_challengeuserdetail_id', 'challengeuserdetail', ['id'], unique=False)
    op.create_table('challengescheduledetail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contents', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name='challengescheduledetail_challenge_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='challengescheduledetail_pkey')
    )
    op.create_index('ix_challengescheduledetail_id', 'challengescheduledetail', ['id'], unique=False)
    op.drop_index(op.f('ix_challenge_user_detail_id'), table_name='challenge_user_detail')
    op.drop_table('challenge_user_detail')
    op.drop_index(op.f('ix_challenge_schedule_detail_id'), table_name='challenge_schedule_detail')
    op.drop_table('challenge_schedule_detail')
    # ### end Alembic commands ###
