"""“change333dd3333”

Revision ID: 847a703b0389
Revises: 290ae7866174
Create Date: 2022-06-17 13:31:34.402186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847a703b0389'
down_revision = '290ae7866174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
