"""Add column last_name to User model

Revision ID: 9674a5b82864
Revises: 4bb91c6be465
Create Date: 2022-06-10 13:39:34.295742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9674a5b82864'
down_revision = '4bb91c6be465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'image')
    # ### end Alembic commands ###
