"""Edit User Model

Revision ID: c9b2cbef3dae
Revises: d4867f3a4c0a
Create Date: 2022-06-09 12:16:47.352271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b2cbef3dae'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('nick_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_full_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_nick_name'), 'user', ['nick_name'], unique=True)
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_nick_name'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'deleted')
    op.drop_column('user', 'nick_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
