"""Add column last_name to User model

Revision ID: d50e1432a435
Revises: 9674a5b82864
Create Date: 2022-06-10 16:46:01.012819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50e1432a435'
down_revision = '9674a5b82864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_accept', sa.Boolean(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_request_id'), 'challenge_request', ['id'], unique=False)
    op.add_column('challenge', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'tags')
    op.drop_index(op.f('ix_challenge_request_id'), table_name='challenge_request')
    op.drop_table('challenge_request')
    # ### end Alembic commands ###
