"""“change123123”

Revision ID: e11d2c020123
Revises: 43eedcb6a89e
Create Date: 2022-06-17 13:28:19.935247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11d2c020123'
down_revision = '43eedcb6a89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
